name: Lost and found in trains

on: [workflow_dispatch]
  # schedule:
  #   - cron: "0 23 * * *"    # Runs at 23:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to GitHub runner.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 # Install the Python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4

      - name: Execute Python scripts
        run: |
          python LF/scraping.py
          python LF/items_lost.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data file
        id: auto-commit-action

